### ISSUE TITLE
RES.getResByUrl不支持await

### ISSUE THREAD

**Issue by LangZhai** [egret-labs/resourcemanager#24]
看了下源码，实际上RES.Resource.getResByUrl返回的已经是一个Promise对象了，为什么在RES.getResByUrl中不返回Promise对象，而是void？

并且RES.instance没有对外开放，如果想用await写法，就只能进行如下操作：
`await new RES.Resource().getResByUrl(source, null, this, RES.ResourceItem.TYPE_IMAGE);`

这样设计的目的是什么呢？这个新模块不就是为了ES2015而生的么？

**Comment by WanderWang** [comment]
这是一个疏忽，我稍后会修复这个问题。

之所以有这个问题，本质原因是需要保持 RES 是向下兼容的，我会将API 改成以下的方式：

```
RES.getResByUrl( url ) // 返回 Promise
RES.getResByUrl ( url ,callback ,this ) // 返回 void
```
