### ISSUE TITLE
resource的demo项目都跑不通

### ISSUE THREAD

**Issue by helojo** [egret-labs/resourcemanager#25]
E:\workspace\html5\test\resourceTest\resourceTest>res build
C:\Users\xy\AppData\Roaming\npm\node_modules\egret-resource-manager\node_modules\vinyl-fs\node_modules\glob-stream\node_modules\glob\node_modules\inflight\inflight.js:39
          RES.apply(null, args)
          ^

ReferenceError: RES is not defined
    at C:\Users\xy\AppData\Roaming\npm\node_modules\egret-resource-manager\node_modules\vinyl-fs\node_modules\glob-stream\node_modules\glob\node_modules\inflight\inflight.js:39:11
    at doNTCallback0 (node.js:419:9)
    at process._tickCallback (node.js:348:13)

**Comment by WanderWang** [comment]
请问您的操作流程是什么？ resourceTest 这个文件夹是怎么生成的？

**Comment by helojo** [comment]
搞定了，谢谢！ Nodejs版本4.4的不行，重装了6.x的就好了。 resourcemanager不支持多个res.json文件这个有什么好的方案解决。 我们现在项目都是多项目混合的方式

**Comment by helojo** [comment]
大神你的微信多少？可以加微信请教一些问题吗？
