### ISSUE TITLE
这个项目估计又是个中间产物

### ISSUE THREAD

**Issue by helojo** [egret-labs/resourcemanager#26]
各种问题，估计要挂

**Comment by WanderWang** [comment]
开发者您好，resourcemanager 是白鹭将会长期维护的项目，并且如果您看提交日志的话也会发现一直有在更新。  

我不知道您的负面情绪是不是由于在15天前提出了一个问题然后无人应答。这确实是我的疏忽，没有关注到这个issue，我可以接下来在您之前提出的问题那里和您继续沟通。
