### ISSUE TITLE
config.json里面组中的key必须是alias吗?

### ISSUE THREAD

**Issue by shunia** [egret-labs/resourcemanager#6]
组指的`groups`.

如果是,那么这里是否只能手动修改?
如果不是,那么这个key还可以是什么?

`alias`本身需要填文件路径这个方式是已经固定了的吗?

**Comment by WanderWang** [comment]
groups里的内容除了 alias 之外也可以是一个文件的文件路径，在新版本中我们不建议开发者使用 alias
