### ISSUE TITLE
这个项目现在达到release状态了吗?

### ISSUE THREAD

**Issue by shunia** [egret-labs/resourcemanager#7]
![image](https://cloud.githubusercontent.com/assets/779430/22637786/fe541922-ec7e-11e6-8021-208d09f89d7f.png)

看到这种会觉得还没到正式发布的样子.
正式发布会直接放进egret的主更新里,还是会一直当做一个额外库的方式?

**Comment by WanderWang** [comment]
未来白鹭引擎的所有库都会在技术上作为一个独立库项目，但是在产品上在版本更新的时候一致发布。

目前 resourcemanager 已经可以在新项目里使用，但是老项目向下兼容仍然存在着若干问题，我们会尽快解决
